package upcraftlp.shadowcreatures;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import upcraftlp.shadowcreatures.init.ShadowCommands;
import upcraftlp.shadowcreatures.init.ShadowConfig;
import upcraftlp.shadowcreatures.proxy.CommonProxy;
import upcraftlp.shadowcreatures.util.ModUpdate;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION)
public class ShadowCreaturesMod {
	
	@Instance(Reference.MOD_ID)
	public static ShadowCreaturesMod instance;
	
	@SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.SERVER_PROXY_CLASS)
	public static CommonProxy proxy;
	
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		System.out.println("[ShadowCreatures] Hello Minecraft!");
		System.out.println("[ShadowCreatures] Preparing to Take over the World!");
		if (!ShadowConfig.init(event))
		{
			System.err.println("=====================================================");
			System.err.println("[ShadowCreaturesMod] FATAL ERROR READING CONFIG FILE");
			System.err.println("Exiting Minecraft.");
			System.err.println("=====================================================");
			
			//NEVER use System.exit(78);
			FMLCommonHandler.instance().exitJava(78, false);
			
			
		}
		System.out.println("[ShadowCreatures] Config loaded.");
		System.out.println("[ShadowCreatures] Checking for available updates...");
		ModUpdate.checkUpdates();
		proxy.preInit(event);
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.name = EnumChatFormatting.AQUA + Reference.MOD_NAME;
		data.description = "Official Shadow Creatures Mod";
		data.credits = "UpcraftLP";
		data.modId = Reference.MOD_ID;
		data.url = "http://minecraft.curseforge.com/projects/shadowcreatures-mod";
		data.version = Reference.VERSION;
		data.authorList.add("UpcraftLP");
		data.authorList.add("The Forge Modding Community");
		data.logoFile = "assets/sc/textures/gui/logo.png";
		
		System.out.println("[ShadowCreatures] Successfully loaded.");
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		System.out.println("[ShadowCreatures] Initializing tweaks.");
		proxy.init(event);
		System.out.println("[ShadowCreatures] Initiated!");
		
	}
	
	@EventHandler
	public void PostInit(FMLPostInitializationEvent event)
	{
		proxy.postInit(event);
		System.out.println("[ShadowCreatures] [HANDSHAKE] Who wants to team up?");
	}
	
	@EventHandler
	public void worldLoad(FMLServerStartingEvent event)
	{
		System.out.println("[ShadowCreatures] Let me take that world for you.");
		ShadowCommands.init(event);
		System.out.println("[ShadowCreatures] This is going to be awesome!");
		
	}
}
